<?php use MF\ViewHelper\Buttons; ?>

<html lang="pt-br">

	<?php require_once('Principais/view_head.php'); ?>

	<body>
		<div class="container">

			<div>
				<h3><?= $this->title; ?></h3>
			</div>

			<div class="menu_index"> 
				<div class="row m-1">
					<?php
						foreach (Buttons::buttonsMenu() as $button) {
							echo $button;
						}
					?>
				</div>
				<div class="row m-1">
					<?php include 'pesquisa-ordenacao.phtml' ?>
				</div>
			</div>

			<?= $this->content(); ?>
		</div>

		<?php include 'modal_form.phtml' ?>
		<?php include 'modal_alerta.phtml' ?>

	</body>

	<?php require_once('Principais/view_bottom.php'); ?>

</html>