<?php use MF\ViewHelper\Buttons; ?>
<?php include "../controle_estoque/vendor/MF/ViewHelper/DataExtract.php"; ?>

<html lang="pt-br">
	
	<?php require_once('Principais/view_head.php'); ?>

	<body>
		<div class="container">

			<div>
				<h3><?= $this->title; ?></h3>
			</div>
			
			    <?= $this->content(); ?>

			<div class="menu_index"> 
				<span>
					<?php
						foreach(Buttons::buttonsCrud() as $button) {
							echo $button;
						}
					?>
				</span>               
			</div>
		</div>

		<?php include 'modal_form.phtml' ?>
		
	</body>

	<?php require_once('Principais/view_bottom.php'); ?>

</html>