<?php use MF\ViewHelper\Buttons; ?>

<html lang="pt-br">

	<?php require_once('Principais/view_head.php'); ?>

	<body>
		<div class="container">

			<div>
				<h3><?= $this->title; ?></h3>
			</div>
			
			<div class="menu_index"> 
				<div class="row m-1">
					<span>
						<?php
							foreach(Buttons::buttonsMenu() as $button) {
								echo $button;
							}
						?>
					</span>

					<span>
						<button class="buttons_menu dropdown-toggle" type="button" id="dropdown-ordenar" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
							Ordenar
						</button>
							<div class="dropdown-menu" aria-labelledby="dropdown-ordenar">
							<!-- aprender como fazer a ordenação e ajustar aqui o que for necessário) -->
								<?php foreach($this->view->ordenar as $option_ordenacao) {

									echo Buttons::buttonsOrdenar($option_ordenacao);
								} ?>
							</div>
					</span>

					<hr>
					<?php include 'pesquisa.phtml' ?>
				</div>
			</div>

			<?= $this->content(); ?>
		</div>

		<?php include 'modal_form.phtml' ?>

	</body>

	<?php require_once('Principais/view_bottom.php'); ?>

</html>