<div class="modal fade" id="id-modal-alerta" tabindex="-1" aria-hidden="true">

  <div class="modal-dialog">

    <div class="modal-content" id="modal-alerta-content">

      <div class="modal-header">

          <h5 class="modal-title"></h5>

          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
          </button>
      </div>
      <div class="modal-body"></div>
      <div class="modal-footer"></div>
    </div>
  </div>
</div>