<?php 
    $options = [
        'pecas' => ['idPeca', 'nomePeca', 'vlrCompraPeca', 'qtdPeca', 'caixaPeca'],
        'caixas' => ['idCaixa', 'nomeCaixa']
    ];
 ?>

<form id="form-pesquisar" style="margin-bottom: 1px;">

    <div class="form-row m-1">

        <div class="col-auto">

            <select class="custom-select" id="base-pesquisa" name="base-pesquisa">
                <option>Escolha</option>
                <?php $n = 0; ?>
                <?php foreach($options['pecas'] as $v) {

                    echo '<option value="pecas-'.$v.'">';
                    echo 'Pecas - '. $v;
                    echo '</otion>';
                } 
                    foreach($options['caixas'] as $v) {

                    echo '<option value="caixas-'.$v.'">';
                    echo 'Caixas - '. $v;
                    echo '</otion>';
                } ?>
            </select>
        </div>
        
            <div class="col-auto custom-control">

            <input type="text" name="item-pesquisa" class="form-control" id="item-pesquisa" placeholder="Digite">
            </div>

        <div class="col-auto">

            <button type="submit" class="btn btn-primary" id="aplicar-pesquisa">Pesquisar</button>
            <button class="btn btn-danger" id="sair-pesquisar">Sair da pesquisa</button>
        </div>
    </div>
</form>