<form method="post"> <!--form aberto aqui e fechado no layout base cruds-->

  <div class="form-group">

    <input name="operation" id="operation" value="editar_caixa" type="hidden">
    <input id="oldId" name="oldId" value="<?= $idCaixa ?>" type="hidden">

    <label for="idCaixa">ID da caixa* (apenas números)</label>

    <input type="number" class="form-control" id="idCaixa" name="idCaixa" value="<?= $idCaixa ?>" required>
  </div>

  <div class="form-group">

    <label for="nomeCaixa">Nome da caixa* (números/letras)</label>

    <input type="text" class="form-control" id="nomeCaixa" name="nomeCaixa" value="<?= $nomeCaixa ?>"required>
  </div>

  <div class="form-group">

    <label for="corCaixa">Cor da caixa (números/letras)</label>

    <input type="text" class="form-control" id="corCaixa" name="corCaixa" value="<?= $corCaixa ?>">
  </div>

  <div class="form-group">

    <label for="descricaoCaixa">Descrição</label>
      
    <textarea class="form-control" id="descricaoCaixa" name="descricaoCaixa" rows="1"><?= $descricaoCaixa ?></textarea>
  </div>