<form method="post" action="/nova_caixa/insert"> <!--form aberto aqui e fechado no layout base cruds-->

  <div class="form-group">

    <input name="operation" id="operation" value="nova_caixa" type="hidden">

    <label for="idCaixa">ID da caixa* (apenas números)</label>

    <input type="number" class="form-control" id="idCaixa" name="idCaixa" required>
  </div>

  <div class="form-group">

    <label for="nomeCaixa">Nome da caixa* (números/letras)</label>

    <input type="text" class="form-control" id="nomeCaixa" name="nomeCaixa" required>
  </div>

  <div class="form-group">

    <label for="corCaixa">Cor da caixa (números/letras)</label>

    <input type="text" class="form-control" id="corCaixa" name="corCaixa">
  </div>

  <div class="form-group">

    <label for="descricaoCaixa">Descrição</label>
      
    <textarea class="form-control" id="descricaoCaixa" name="descricaoCaixa" rows="1"></textarea>
  </div>