<?php use MF\ViewHelper\Buttons; ?>

<div class="modal-header">

    <h5 class="modal-title"><?= $this->titulo ?></h5>

    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form action="">

    <div class="modal-body">
        <?php foreach($this->matriz_data as $caixas): ?>
            <div>
                <input type="checkbox" name="caixa" value="<?= $caixas['idCaixa'] ?>">
            </div>

            <div>
                <span><?= $caixas['nomeCaixa'] ?></span>
            </div>
        <?php endforeach; ?>
    </div>
    <div class="modal-footer">
        <?php
            foreach(Buttons::buttons_modal_crud($this->view->buttons) as $button) {
                echo $button;
            }
        ?>
    </div>
</form>