<?php use MF\ViewHelper\NumbersHelper; ?>

<form method="post">

  <div class="form-group">

    <input name="operation" id="operation" value="editar_peca" type="hidden">
    <input id="oldId" name="oldId" value="<?= $peca_editar['idPeca'] ?>" type="hidden">

    <label for="idPeca">ID da peça* (números ou letras)</label>

    <input  type="text" 
            class="form-control" 
            id="idPeca" 
            name="idPeca" 
            value="<?= $peca_editar['idPeca'] ?>" 
            required 
            <?php if($this->view->opcoes['disabled']) echo 'readonly' ?>>
  </div>

  <div class="form-group">

    <label for="nomePeca">Nome da peça* (números/letras)</label>

    <input type="text" class="form-control" id="nomePeca" name="nomePeca" value="<?= $peca_editar['nomePeca'] ?>" required>
  </div>

  <div class="form-group">

    <label for="vlrCompraPeca">Valor pago pela peça* (apenas números)</label>

    <input type="text" class="form-control vlr-compra-peca" maxlength="9" id="vlrCompraPeca" name="vlrCompraPeca" value="<?= NumbersHelper::formatUStoBR($peca_editar['vlrCompraPeca']); ?>" required>
  </div>

  <div class="form-group">

    <label for="qtdPeca">Qtd de peças compradas* (apenas números)</label>

    <input type="text" class="form-control" id="qtdPeca" name="qtdPeca" value="<?= $peca_editar['qtdPeca'] ?>" required>
  </div>

  <div class="form-group">

    <label for="caixaPeca">Caixa onde está a peça *</label>
      
    <select class="form-control" id="caixaPeca" name="caixaPeca" required>
    
      <option value="">Selecione</option>

      <?php 
        
        foreach($lista_caixas as $key => $value) {

          $selected = '';
          if ($value["idCaixa"] == $peca_editar['caixaPeca']) $selected = 'selected';  

          echo '<option id="'.$value["idCaixa"].'" value="'.$value["idCaixa"].'" '.$selected.'>'.$value["nomeCaixa"].'</option>';
      } ?>
    </select>
  </div>

  <div class="form-group" id="fotoPeca">

    <label for="fotoPeca">Foto .JPG</label>
    <input type="file" class="form-control" id="fotoPeca" name="fotoPeca" accept="image/jpeg">

    <span class="h6">Imagem atual: <?= $peca_editar['fotoPeca'] ? $peca_editar['fotoPeca'] : 'Nenhuma imagem' ?></span>

    <?php if(isset($fotoPeca) && $fotoPeca != ''): ?>
      <hr><button type="button" id="excluir-img-atual">Excluir imagem atual</button>
    <?php endif; ?>  
  </div>
</form>