<form method="post" action="/nova_peca/insert" enctype="multipart/form-data">

  <div class="form-group">
    <input name="operation" id="operation" value="nova_peca" type="hidden">
  </div>

  <div class="form-group">

    <label for="nomePeca">Nome da peça* (números/letras)</label>

    <input type="text" class="form-control" id="nomePeca" name="nomePeca" required>
    <br>
    <select class="form-control select2">
      <option value=""> Pesquise aqui se uma peça já existe </option>
      <?php foreach($lista_pecas as $key => $value): ?>
        <option value=""> <?= 'id: ' . $value->idPeca . ' - nome: ' . $value->nomePeca ?> </option>
      <?php endforeach; ?>
    </select>
  </div>

  <div class="form-group">

    <label for="vlrCompraPeca">Valor pago pela peça (apenas números)</label>

    <input type="text" class="form-control" maxlength="9" id="vlrCompraPeca" name="vlrCompraPeca">
  </div>

  <div class="form-group">

    <label for="qtdPeca">Qtd de peças compradas* (apenas números)</label>

    <input type="text" class="form-control" id="qtdPeca" name="qtdPeca" required>
  </div>

  <div class="form-group">

    <label for="idCaixa">Caixa onde está a peça *</label>

    <select class="form-control" id="idCaixa" name="idCaixa" required>

      <option value="">Selecione</option>

      <?php foreach($lista_caixas as $key => $value) {

        echo '<option id="'.$value["idCaixa"].'" value="'.$value["idCaixa"].'">'.$value["nomeCaixa"].'</option>';
      } ?>
    </select>
  </div>

  <div class="form-group">

    <label for="fotoPeca">Foto .JPG</label>

    <input type="file" class="form-control" id="fotoPeca" name="fotoPeca" accept="image/jpeg">
  </div>
</form>