<form method="post">

  <div class="form-group">

    <input name="operation" id="operation" value="baixar_peca" type="hidden">

    <?php foreach($this->matriz_data as $peca => $attr): ?>
    
      <div class="form-row mb-3">

        <div class="form-group col-12 col-sm-3">

          <label for="idPeca[]">ID Peça</label>
          <input type="text" class="form-control" id="idPeca-<?= $attr[0]['idPeca']; ?>" value="<?= $attr[0]['idPeca']; ?>" name="idPeca[]" readonly>
        </div>
        
        <div class="form-group col-12 col-sm-3">

          <label for="nomePeca[]">Nome Peça</label>
          <input type="text" class="form-control" id="idNomePeca-<?= $attr[0]['idPeca']; ?>" value="<?= $attr[0]['nomePeca']; ?>" name="nomePeca[]" readonly>
        </div>

        <div class="form-group col-12 col-sm-3">

          <label for="dataUso[]">Data baixa</label>
          <input type="text" class="form-control input-data" id="idDataBaixa-<?= $attr[0]['nomePeca']; ?>" value="" name="dataUso[]" required>
        </div>

        <div class="form-group col-12 col-sm-3">

          <label for="qtdUso[]">Quantidade baixa</label>
          <select class="form-control" id="idQtdPeca-<?= $attr[0]['idPeca']; ?>" value="" name="qtdUso[]" required>
            <option>Escolha</option>
            <?php for($i = 0; $i <= $attr[0]['qtdPeca']; $i++): ?>
              <option><?= $i ?></option>
            <?php endfor; ?>  
          </select>
        </div>
      </div>
    <?php endforeach; ?>    
</form>