<form method="post">

  <div class="form-group">

    <input name="operation" id="operation" value="editar_peca" type="hidden">
    <input id="oldId" name="oldId" value="<?= $idPeca ?>" type="hidden">

    <label for="idPeca">ID da peça* (apenas números)</label>

    <input type="number" class="form-control" id="idPeca" name="idPeca" value="<?= $idPeca ?>" required>
  </div>

  <div class="form-group">

    <label for="nomePeca">Nome da peça* (números/letras)</label>

    <input type="text" class="form-control" id="nomePeca" name="nomePeca" value="<?= $nomePeca ?>" required>
  </div>

  <div class="form-group">

    <label for="vlrCompraPeca">Valor pago pela peça* (apenas números)</label>

    <input type="text" class="form-control" maxlength="9" id="vlrCompraPeca" name="vlrCompraPeca" value="<?= $vlrCompraPeca ?>" required>
  </div>

  <div class="form-group">

    <label for="qtdPeca">Qtd de peças compradas* (apenas números)</label>

    <input type="text" class="form-control" id="qtdPeca" name="qtdPeca" value="<?= $qtdPeca ?>" required>
  </div>

  <div class="form-group">

    <label for="caixaPeca">Caixa onde está a peça *</label>
      
    <select class="form-control" id="caixaPeca" name="caixaPeca" required>
    
      <option value="">Selecione</option>

      <?php 
        
        foreach($this->matriz_data as $key => $value) {

          $selected = '';
          if($value["idCaixa"] == $caixaPeca) $selected = 'selected';  

          echo '<option id="'.$value["idCaixa"].'" value="'.$value["idCaixa"].'" '.$selected.'>'.$value["nomeCaixa"].'</option>';
      } ?>
    </select>
  </div>
</form>