<form method="post" action="/nova_peca/insert"> <!--form aberto aqui e fechado no layout base cruds-->

  <div class="form-group">

    <input name="operation" id="operation" value="nova_peca" type="hidden">

    <label for="idPeca">ID da peça* (apenas números)</label>

    <input type="number" class="form-control" id="idPeca" name="idPeca" required>
  </div>
  
  <?php echo $nome; ?>

  <div class="form-group">

    <label for="nomePeca">Nome da peça* (números/letras)</label>

    <input type="text" class="form-control" id="nomePeca" name="nomePeca" required>
  </div>

  <div class="form-group">

    <label for="vlrCompraPeca">Valor pago pela peça (apenas números)</label>

    <input type="text" class="form-control" id="vlrCompraPeca" name="vlrCompraPeca">
  </div>

  <div class="form-group">

    <label for="caixaPeca">Caixa onde está a peça</label>
      
    <select class="form-control" id="caixaPeca" name="caixaPeca">
        <option>Default select</option>
    </select>
  </div>