<?php use MF\ViewHelper\Buttons; ?>

<div class="modal-header">

    <h5 class="modal-title"><?= $this->titulo ?></h5>

    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form id="form-editar-caixa" method="POST">

  <div class="modal-body">

    <div class="form-group">

        <input name="operation" id="operation" value="editar_caixa" type="hidden">
        <input id="oldId" name="oldId" value="<?= $caixa['idCaixa'] ?>" type="hidden">

        <label for="idCaixa">ID da caixa* (números ou letras)</label>

        <input 
          type="text" 
          class="form-control" 
          id="idCaixa" 
          name="idCaixa" 
          value="<?= $caixa['idCaixa'] ?>" 
          required
          <?php if ($this->view->opcoes['disabled']) echo 'disabled' ?>
        >
    </div>

    <div class="form-group">

        <label for="nomeCaixa">Nome da caixa* (números/letras)</label>

        <input type="text" class="form-control" id="nomeCaixa" name="nomeCaixa" value="<?= $caixa['nomeCaixa'] ?>"required>
    </div>

    <div class="form-group">

        <label for="corCaixa">Cor da caixa (números/letras)</label>

        <input type="text" class="form-control" id="corCaixa" name="corCaixa" value="<?= $caixa['corCaixa'] ?>">
    </div>

    <div class="form-group">

        <label for="descricaoCaixa">Descrição</label>
          
        <textarea class="form-control" id="descricaoCaixa" name="descricaoCaixa" rows="1"><?= $caixa['descricaoCaixa'] ?></textarea>
    </div>
  </div>  
</form>   
<div class="modal-footer">
    <?php
        foreach(Buttons::buttons_modal_crud($this->view->operacao) as $button) {
            echo $button;
        }
    ?>
</div>