<form method="post" action="/nova_caixa/insert">

  <div class="form-group">
    <input name="operation" id="operation" value="nova_caixa" type="hidden">
  </div>

  <div class="form-group">

    <label for="nomeCaixa">Nome da caixa* (números/letras)</label>

    <input type="text" class="form-control" id="nomeCaixa" name="nomeCaixa" required>
    <br>
    <select class="form-control select2">
      <option value=""> Pesquise aqui se uma caixa já existe </option>
      <?php foreach($caixas as $key => $value): ?>
        <option value=""> <?= 'id: ' . $value['idCaixa']. ' - nome: ' . $value['nomeCaixa'] ?> </option>
      <?php endforeach; ?>
    </select> 
  </div>

  <div class="form-group">

    <label for="corCaixa">Cor da caixa (números/letras)</label>

    <input type="text" class="form-control" id="corCaixa" name="corCaixa">
  </div>

  <div class="form-group">

    <label for="descricaoCaixa">Descrição</label>
      
    <textarea class="form-control" id="descricaoCaixa" name="descricaoCaixa" rows="1"></textarea>
  </div>
</form>  