<?php use MF\ViewHelper\Buttons; ?>

<div class="modal-header">

    <h5 class="modal-title"><?= $this->titulo ?></h5>

    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<form id="form-todas-caixas" method="POST">

    <input type="hidden" id="operacao" name="operacao" value="<?= $this->view->operacao ?>">

    <div class="modal-body">
        <?php foreach($caixas as $caixa): ?>
            <div class="form-group form-check">

                <?php if($this->view->operacao == 'apagar') {
                        $tipo = 'checkbox'; 
                    } else {
                        $tipo = 'radio'; } ?>

                <input type="<?=$tipo?>" class="form-check-input" name="caixa[]" value="<?= $caixa['idCaixa'] ?>" id="id-<?=$caixa['idCaixa']?>">
                <label class="form-check-label" for="id-<?=$caixa['idCaixa']?>"><?= $caixa['nomeCaixa'] ?></label>
            </div>
        <?php endforeach; ?>
    </div>
</form>   
<div class="modal-footer">
    <?php
        foreach(Buttons::buttonsModalCrud($this->view->operacao) as $button) {
            echo $button;
        }
    ?>
</div>