<main class="conteudo_principal">

  <form method="POST" id="form-index">

    <table>

      <thead>

        <tr>
          <td>Selecionar</td>
        <?php foreach($this->view->atributos as $index => $valor) { ?>
            <td>
              <?= $valor ?>
            </td>
          <?php } ?>
        </tr>    
      </thead>
      
      <tbody>
        <?php foreach($this->view->dados as $index => $valor) { ?>
          <tr>
            <td class="selects">
              <input type="checkbox" class="pecas" name="idPeca[]" value="<?= $valor->idPeca ?>">
            </td>
            <td>
              <?= $valor->idPeca ?>
            </td>
            <td>
              <?= $valor->nomePeca ?>
            </td>
            <td>
              <?= $valor->vlrCompraPeca ?>
            </td>
            <td>
              <?= $valor->qtdPeca ?>
            </td>
            <td>
              <?= $valor->caixaPeca ?>
            </td>
            <td>
              <?= $valor->nomeCaixa ?>
            </td>
          </tr>        
        <?php } ?>
      </tbody>
    </table>
  </form>  
</main>