<?php use MF\ViewHelper\Buttons; ?>

<html lang="pt-br">
	
	<head>
		<meta charset="utf-8">

		<title><?= $this->title; ?></title>

		<link rel="stylesheet" href="css/bootstrap.css">
		<link rel="stylesheet" href="css/custom.css">
	</head>

	<body>
		<div class="container">

			<div>
				<h3><?= $this->title; ?></h3>
			</div>
			
			    <?= $this->content(); ?>

                <div class="menu_index"> 
                    <span>
                        <?php
                            foreach(Buttons::buttonsCrud() as $button) {
                                echo $button;
                            }
                        ?>
                    </span>

                    <span>Usuário</span>

                    <span>Sair</span>
               
                </form><!--form aberto no content() e fechado aqui-->
			</div>
		</div>
	</body>

	<script src="js/jquery.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="js/bootstrap.js"></script>
	<script src="js/custom.js"></script>
</html>